info: EndToEnd，efficientnet_b4输出128维，32维压缩，eval使用重建去查询原始，图像归一化使用ImageNet均值标准差，更改为pytorch的RandomErasing
model_depth: b4
feature_dim: 128
compress_dim: 32
device: 0
epochs: 120
early_stopping: 0
batch_size: 128
lr: 0.00035
weight_decay: 0.0005
warm_up_step: 10
source: /nfs3-p1/zsxm/naic/rematch/train/
save_cp: false
load_model: False