info: 只训练特征提取，efficientnet_b4输出180维，优化器换Ranger，增加自然数据集
model_name: efficientnet_b4(num_classes={}, pretrained='.details/checkpoints/efficientnet_b4.pth')
feature_dim: 180
device: 3
epochs: 120
early_stopping: 0
batch_size: 64
lr: 0.00035
weight_decay: 0.0005
milestones: [30, 55]
gamma: 0.1
warmup_factor: 0.01
warmup_iters: 10
source: /disk1/zsxm/datasets/naic/multidataset
save_cp: false
start_epoch: 0
load_model: False
load_optimizer: False
load_scheduler: False