info: 64字节
intermediate_dim: 16
input_dim: 2048
output_dim: 2048
memory: true
not_zero: false
device: 1
epochs: 1000
early_stopping: 100
batch_size: 512
lr: 0.1
source: /nfs3-p2/zsxm/naic/preliminary/train/
save_cp: false
load_encoder: False
load_decoder: False